"""autogenerated by genpy from wifi_ddwrt/Network.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Network(genpy.Message):
  _md5sum = "cbd4630ce96fafe4e30405354c4f82d3"
  _type = "wifi_ddwrt/Network"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string macattr
string essid
string frequency
int32 channel
int32 rssi
int32 noise
int32 beacon

"""
  __slots__ = ['macattr','essid','frequency','channel','rssi','noise','beacon']
  _slot_types = ['string','string','string','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       macattr,essid,frequency,channel,rssi,noise,beacon

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Network, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.macattr is None:
        self.macattr = ''
      if self.essid is None:
        self.essid = ''
      if self.frequency is None:
        self.frequency = ''
      if self.channel is None:
        self.channel = 0
      if self.rssi is None:
        self.rssi = 0
      if self.noise is None:
        self.noise = 0
      if self.beacon is None:
        self.beacon = 0
    else:
      self.macattr = ''
      self.essid = ''
      self.frequency = ''
      self.channel = 0
      self.rssi = 0
      self.noise = 0
      self.beacon = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.macattr
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.essid
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.frequency
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_4i.pack(_x.channel, _x.rssi, _x.noise, _x.beacon))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.macattr = str[start:end].decode('utf-8')
      else:
        self.macattr = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.essid = str[start:end].decode('utf-8')
      else:
        self.essid = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frequency = str[start:end].decode('utf-8')
      else:
        self.frequency = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.channel, _x.rssi, _x.noise, _x.beacon,) = _struct_4i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.macattr
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.essid
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.frequency
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_4i.pack(_x.channel, _x.rssi, _x.noise, _x.beacon))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.macattr = str[start:end].decode('utf-8')
      else:
        self.macattr = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.essid = str[start:end].decode('utf-8')
      else:
        self.essid = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frequency = str[start:end].decode('utf-8')
      else:
        self.frequency = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.channel, _x.rssi, _x.noise, _x.beacon,) = _struct_4i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4i = struct.Struct("<4i")
