/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/mig-ly/catkin_ws/src/wifi_ddwrt/msg/Network.msg
 *
 */


#ifndef WIFI_DDWRT_MESSAGE_NETWORK_H
#define WIFI_DDWRT_MESSAGE_NETWORK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wifi_ddwrt
{
template <class ContainerAllocator>
struct Network_
{
  typedef Network_<ContainerAllocator> Type;

  Network_()
    : macattr()
    , essid()
    , frequency()
    , channel(0)
    , rssi(0)
    , noise(0)
    , beacon(0)  {
    }
  Network_(const ContainerAllocator& _alloc)
    : macattr(_alloc)
    , essid(_alloc)
    , frequency(_alloc)
    , channel(0)
    , rssi(0)
    , noise(0)
    , beacon(0)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _macattr_type;
  _macattr_type macattr;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _essid_type;
  _essid_type essid;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frequency_type;
  _frequency_type frequency;

   typedef int32_t _channel_type;
  _channel_type channel;

   typedef int32_t _rssi_type;
  _rssi_type rssi;

   typedef int32_t _noise_type;
  _noise_type noise;

   typedef int32_t _beacon_type;
  _beacon_type beacon;




  typedef boost::shared_ptr< ::wifi_ddwrt::Network_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wifi_ddwrt::Network_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct Network_

typedef ::wifi_ddwrt::Network_<std::allocator<void> > Network;

typedef boost::shared_ptr< ::wifi_ddwrt::Network > NetworkPtr;
typedef boost::shared_ptr< ::wifi_ddwrt::Network const> NetworkConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wifi_ddwrt::Network_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wifi_ddwrt::Network_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wifi_ddwrt

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/cmake/../msg'], 'wifi_ddwrt': ['/home/mig-ly/catkin_ws/src/wifi_ddwrt/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wifi_ddwrt::Network_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wifi_ddwrt::Network_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wifi_ddwrt::Network_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wifi_ddwrt::Network_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wifi_ddwrt::Network_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wifi_ddwrt::Network_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wifi_ddwrt::Network_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cbd4630ce96fafe4e30405354c4f82d3";
  }

  static const char* value(const ::wifi_ddwrt::Network_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcbd4630ce96fafe4ULL;
  static const uint64_t static_value2 = 0xe30405354c4f82d3ULL;
};

template<class ContainerAllocator>
struct DataType< ::wifi_ddwrt::Network_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wifi_ddwrt/Network";
  }

  static const char* value(const ::wifi_ddwrt::Network_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wifi_ddwrt::Network_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string macattr\n\
string essid\n\
string frequency\n\
int32 channel\n\
int32 rssi\n\
int32 noise\n\
int32 beacon\n\
\n\
";
  }

  static const char* value(const ::wifi_ddwrt::Network_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wifi_ddwrt::Network_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.macattr);
      stream.next(m.essid);
      stream.next(m.frequency);
      stream.next(m.channel);
      stream.next(m.rssi);
      stream.next(m.noise);
      stream.next(m.beacon);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Network_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wifi_ddwrt::Network_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wifi_ddwrt::Network_<ContainerAllocator>& v)
  {
    s << indent << "macattr: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.macattr);
    s << indent << "essid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.essid);
    s << indent << "frequency: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frequency);
    s << indent << "channel: ";
    Printer<int32_t>::stream(s, indent + "  ", v.channel);
    s << indent << "rssi: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rssi);
    s << indent << "noise: ";
    Printer<int32_t>::stream(s, indent + "  ", v.noise);
    s << indent << "beacon: ";
    Printer<int32_t>::stream(s, indent + "  ", v.beacon);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WIFI_DDWRT_MESSAGE_NETWORK_H
