/c_width: 1
/c_height: 1
/database: fingerprints.pkl
/num_aps: 5
/macaddr_0: "08:60:6e:cc:79:04"
/essid_0: cob-developer
/macaddr_1: "84:c9:b2:6a:80:e8"
/essid_1: cob3-3-extern
/macaddr_2: "84:c9:b2:6a:81:30"
/essid_2: desire-extern 
/macaddr_3: "00:0b:0e:c9:03:83" 
/essid_3: IZS-Campus
/macaddr_4: "00:0b:0e:c9:38:c1"
/essid_4: eduroam
/macaddr_5: "999"
/essid_5: nil
/macaddr_6: "999"
/essid_6: nil
/macaddr_7: "999"
/essid_7: nil
/macaddr_8: "999"
/essid_8: nil
/macaddr_9: "999"
/essid_9: nil

