router :
     hostname : "10.0.1.20"
     username : admin
     password : test


cell size :
     c_width  : 0.5
     c_height : 0.5

database : fingerprints_1,1.pkl

percentage_taken : 0.9

access points :
     ap_no   : 0 
     macaddr : "08:60:6e:cc:79:04"
     essid   : cob-developer

     ap_no   : 1
     macaddr : "84:c9:b2:6a:80:e8"
     essid   : cob3-3-extern

     ap_no   : 2
     macaddr : "84:c9:b2:6a:81:30"
     essid   : desire-extern

     ap_no   : 3
     macaddr : "00:0b:0e:c9:03:83"
     essid   : IZS-Campus

     ap_no   : 4
     macaddr : "00:0b:0e:c9:38:c1"
     essid   : eduroam

